[package]
name = "janus-plugin-sfu"
description = "Janus SFU for game networking."
version = "0.1.0"
authors = ["Marshall Quander <marshall@quander.me>"]
repository = "https://github.com/mozilla/janus-plugin-sfu"
license = "MPL-2.0"
publish = false

[lib]
crate_type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
atom = "0.3"
janus-plugin = { git = "https://github.com/mozilla/janus-plugin-rs" }
lazy_static = "1.0"
multimap = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rust-ini = "0.10"
jsonwebtoken = "5.0"
